#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : golang-github-coreos-go-systemd
Version  : 7b2428fec40033549c68f54e26e89e7ca9a9ce31
Release  : 4
URL      : https://github.com/coreos/go-systemd/archive/7b2428fec40033549c68f54e26e89e7ca9a9ce31.tar.gz
Source0  : https://github.com/coreos/go-systemd/archive/7b2428fec40033549c68f54e26e89e7ca9a9ce31.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
BuildRequires : go

%description
# go-systemd
[![Build Status](https://travis-ci.org/coreos/go-systemd.png?branch=master)](https://travis-ci.org/coreos/go-systemd)
[![godoc](https://godoc.org/github.com/coreos/go-systemd?status.svg)](http://godoc.org/github.com/coreos/go-systemd)

%prep
%setup -q -n go-systemd-7b2428fec40033549c68f54e26e89e7ca9a9ce31

%build

%install
gopath="/usr/lib/golang"
library_path="github.com/coreos/go-systemd"
rm -rf %{buildroot}
install -d -p %{buildroot}${gopath}/src/${library_path}/
for file in $(find . -iname "*.go" -o -iname "*.h" -o -iname "*.c") ; do
     echo ${file}
     install -d -p %{buildroot}${gopath}/src/${library_path}/$(dirname $file)
     cp -pav $file %{buildroot}${gopath}/src/${library_path}/$file
done


%files
%defattr(-,root,root,-)
/usr/lib/golang/src/github.com/coreos/go-systemd/activation/files.go
/usr/lib/golang/src/github.com/coreos/go-systemd/activation/files_test.go
/usr/lib/golang/src/github.com/coreos/go-systemd/activation/listeners.go
/usr/lib/golang/src/github.com/coreos/go-systemd/activation/listeners_test.go
/usr/lib/golang/src/github.com/coreos/go-systemd/activation/packetconns.go
/usr/lib/golang/src/github.com/coreos/go-systemd/activation/packetconns_test.go
/usr/lib/golang/src/github.com/coreos/go-systemd/daemon/sdnotify.go
/usr/lib/golang/src/github.com/coreos/go-systemd/dbus/dbus.go
/usr/lib/golang/src/github.com/coreos/go-systemd/dbus/dbus_test.go
/usr/lib/golang/src/github.com/coreos/go-systemd/dbus/methods.go
/usr/lib/golang/src/github.com/coreos/go-systemd/dbus/methods_test.go
/usr/lib/golang/src/github.com/coreos/go-systemd/dbus/properties.go
/usr/lib/golang/src/github.com/coreos/go-systemd/dbus/set.go
/usr/lib/golang/src/github.com/coreos/go-systemd/dbus/set_test.go
/usr/lib/golang/src/github.com/coreos/go-systemd/dbus/subscription.go
/usr/lib/golang/src/github.com/coreos/go-systemd/dbus/subscription_set.go
/usr/lib/golang/src/github.com/coreos/go-systemd/dbus/subscription_set_test.go
/usr/lib/golang/src/github.com/coreos/go-systemd/dbus/subscription_test.go
/usr/lib/golang/src/github.com/coreos/go-systemd/examples/activation/activation.go
/usr/lib/golang/src/github.com/coreos/go-systemd/examples/activation/httpserver/httpserver.go
/usr/lib/golang/src/github.com/coreos/go-systemd/examples/activation/listen.go
/usr/lib/golang/src/github.com/coreos/go-systemd/examples/activation/udpconn.go
/usr/lib/golang/src/github.com/coreos/go-systemd/journal/journal.go
/usr/lib/golang/src/github.com/coreos/go-systemd/login1/dbus.go
/usr/lib/golang/src/github.com/coreos/go-systemd/login1/dbus_test.go
/usr/lib/golang/src/github.com/coreos/go-systemd/machine1/dbus.go
/usr/lib/golang/src/github.com/coreos/go-systemd/machine1/dbus_test.go
/usr/lib/golang/src/github.com/coreos/go-systemd/sdjournal/journal.go
/usr/lib/golang/src/github.com/coreos/go-systemd/sdjournal/journal_test.go
/usr/lib/golang/src/github.com/coreos/go-systemd/sdjournal/read.go
/usr/lib/golang/src/github.com/coreos/go-systemd/unit/deserialize.go
/usr/lib/golang/src/github.com/coreos/go-systemd/unit/deserialize_test.go
/usr/lib/golang/src/github.com/coreos/go-systemd/unit/end_to_end_test.go
/usr/lib/golang/src/github.com/coreos/go-systemd/unit/escape.go
/usr/lib/golang/src/github.com/coreos/go-systemd/unit/escape_test.go
/usr/lib/golang/src/github.com/coreos/go-systemd/unit/option.go
/usr/lib/golang/src/github.com/coreos/go-systemd/unit/option_test.go
/usr/lib/golang/src/github.com/coreos/go-systemd/unit/serialize.go
/usr/lib/golang/src/github.com/coreos/go-systemd/unit/serialize_test.go
/usr/lib/golang/src/github.com/coreos/go-systemd/util/util.go
